.SUFFIXES: .o .mod .f08

# Compiler
FC  = gfortran 

# Flags
OFLAGS = -O3 -funroll-loops # -Optimization
DFLAGS = -g3 -finit-real=snan -fbacktrace -fcheck=all -ffpe-summary=all # debugging
WFLAGS = -Wall -Wextra -pedantic -std=f2008 -fall-intrinsics -Warray-temporaries -Wcharacter-truncation -Wconversion-extra # warnings

# Compiling rules, .o and .mod files both depend on .f08 and are both produced by a single invocation of gfortran
%.o %.mod: %.f08
	$(FC) -o $@ $(OFLAGS) $(WFLAGS) -c $<

# Object modules
OBJ = element_data_type.o sort.o cut_molecule.o variational_mesh.o main.o

# Default targets
all: Variational_Mesh

# 'Quantum_Now' (target) depends on all OBJ files and main.o
Variational_Mesh: $(OBJ)
	$(FC) -o $@ $(OFLAGS) $(WFLAGS) $^

# Deletes files generated by compilation
clean:
	rm -f *.o *.mod Variational_Mesh BoxInfoOutput.DAT

run: Variational_Mesh
	./Variational_Mesh

# Dependencies
element_data_type.mod: element_data_type.f08
cut_molecule.mod: cut_molecule.f08 element_data_type.mod cut_molecule.f08 sort.mod
sort.mod: sort.f08 element_data_type.mod
variational_mesh.mod: variational_mesh.f08 element_data_type.mod cut_molecule.mod

element_data_type.o: element_data_type.f08
cut_molecule.o: cut_molecule.f08 element_data_type.mod cut_molecule.f08 sort.mod
sort.o: sort.f08 element_data_type.mod
variational_mesh.o: variational_mesh.f08 element_data_type.mod cut_molecule.mod
main.o: variational_mesh.mod

